version: "3.8"
services:
  frontend:
    container_name: ctims-web
    build:
      context: ./
      args:
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_API_URL: ${NEXTAUTH_API_URL}
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    networks:
      - my-network

  backend:
    container_name: ctims-api
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
      args:
        KEYCLOAK_REALM: ${KEYCLOAK_REALM}
        KEYCLOAK_URL: ${KEYCLOAK_URL}
        KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
        KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
        KEYCLOAK_ADMIN_CLIENT_ID: ${KEYCLOAK_ADMIN_CLIENT_ID}
        KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
        KEYCLOAK_TOKEN_ENDPOINT: ${KEYCLOAK_TOKEN_ENDPOINT}
        KEYCLOAK_CLIENT_UUID: ${KEYCLOAK_CLIENT_UUID}
        PRISMA_FIELD_ENCRYPTION_KEY: ${PRISMA_FIELD_ENCRYPTION_KEY}
        MM_API_URL: ${MM_API_URL}
    environment:
      DATABASE_URL: mysql://ctims:ctims@database:3306/ctims
    ports:
      - "3333:3333"
    restart: on-failure
    networks:
      - my-network
networks:
  my-network:
