version: "3.8"

services:
  mm_api:
    image: docker-registry.uhn.ca:443/matchminer-api:a62fb924-1356-4c01-b088-1b99491bd12c
    ports:
      - "5000:5000"
    restart: on-failure
    networks:
      - my-network

  mm_mongo_db:
    container_name: mm_mongo_db
    image: mongo:3.6.10
    restart: on-failure
    ports:
      - "27018:27017"
    networks:
        - my-network
    volumes:
      - mm-mongo-db:/data/db

volumes:
  mm-mongo-db:

networks:
    my-network:
