{{- $fullName := include "thischart.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "thischart.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
spec:
  rules:
    - host: "ctims-web.{{ .Values.domain }}"
      http:
        paths:
          - pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: ctimsweb
    - host: "ctims-api.{{ .Values.domain }}"
      http:
        paths:
          - pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: ctimsapi
    - host: "mm-api.{{ .Values.domain }}"
      http:
        paths:
        - pathType: "ImplementationSpecific"
          backend:
            service:
              name: {{ $fullName }}
              port:
                name: mm-api
