apiVersion: v1
kind: Service
metadata:
  name: {{ include "thischart.fullname" . }}
  labels:
{{ include "thischart.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ctimsweb.port }}
      targetPort: 3000
      name: ctimsweb
    - port: {{ .Values.ctimsapi.port }}
      targetPort: 3333
      name: ctimsapi
    - port: 5000
      targetPort: 5000
      name: mm-api
  selector:
    app.kubernetes.io/name: {{ include "thischart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
